# YOLO Dataset Config - Fold 1
# Train: video_0, video_2 | Val: video_1

path: ../data/folds/fold_1  # dataset root dir
train: train/images  # train images (relative to 'path')
val: val/images  # val images (relative to 'path')

# Classes
nc: 1  # number of classes
names:
  0: starfish  # Crown-of-Thorns Starfish (COTS)
